# Generated by Django 4.2 on 2023-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="conclusion",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="custom_fields",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="executive_summary",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="fields_order",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="methodology",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="report_summary",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="tested_environment",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="tools_used",
        ),
        migrations.RemoveField(
            model_name="reportdatafiller",
            name="vulnerabilities",
        ),
        migrations.AddField(
            model_name="reportdatafiller",
            name="report_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportdatafiller",
            name="report_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportdatafiller",
            name="report_sections",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportdatafiller",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
